name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: Linting
        run: |
          go get -u golang.org/x/lint/golint
          cd core
          $(which golint 2> /dev/null || echo /home/runner/go/bin/golint) -set_exit_status ./...
      - name: CLI Build
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_API_USER: ${{ secrets.GH_API_USER }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          /bin/sh automation/build.cli.sh
          /bin/sh automation/publish.cli.sh
      - name: CLI Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: phytofy.exe
          path: phytofy.exe
      - name: IoT Build
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          REGISTRY_PREFIX: ${{ secrets.REGISTRY_PREFIX }}
          VERSION_SEPARATOR: ${{ secrets.VERSION_SEPARATOR }}
          GH_API_USER: ${{ secrets.GH_API_USER }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          /bin/sh automation/build.iot.sh
          /bin/sh automation/publish.iot.sh
          rm /home/runner/.docker/config.json
